### ISSUE TITLE
How to install tree-sitter-dbml in neovim

### ISSUE THREAD

**Issue by chiendo97** [dynamotn/tree-sitter-dbml#1]
Hi @dynamotn 

I just found your tree-sitter grammar for dbml on the internet. 

May I ask you what the proper way to install it for neovim? 

Thanks.

**Comment by namtdtopcv** [comment]
@chiendo97 Because it is under development version, so I don't want to create a PR for `nvim-treesitter`.
If you want to use, you must do these steps:
- Add filetype for `*.dbml` files, like this 
```lua
vim.filetype.add({
  pattern = {
    ['.*%.dbml'] = 'dbml',
  },
})
```
- Add parser when setup/config `tree-sitter`, via `lazy` or `packer`:
```lua
local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
parser_config.dbml = {
  install_info = {
    url = "https://github.com/dynamotn/tree-sitter-dbml",
    branch = 'main',           
    files = { 'src/parser.c' },
  },
  filetype = "dbml",
}
```
Hope this useful for you!

**Comment by dynamotn** [comment]
@chiendo97 Sorry for the late response
Because it is under development version, so I don't want to create a PR for `nvim-treesitter`.
If you want to use, you must do these steps:
- Add filetype for `*.dbml` files, like this 
```lua
vim.filetype.add({
  pattern = {
    ['.*%.dbml'] = 'dbml',
  },
})
```
- Add parser when setup/config `tree-sitter`, via `lazy` or `packer`:
```lua
local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
parser_config.dbml = {
  install_info = {
    url = "https://github.com/dynamotn/tree-sitter-dbml",
    branch = 'main',           
    files = { 'src/parser.c' },
  },
  filetype = "dbml",
}
```
- Register parser
```lua
vim.treesitter.language.register('dbml', 'dbml')
```
- Restart your neovim, and run `:TSInstall dbml`
Hope this useful for you!
